_target_: tropt.optimizer.gaslite_optimizer.GASLITEOptimizer
_partial_: true

# Original paper parameters:
num_steps: 100
n_candidates: 128
n_grad: 10  # while original paper used 50, we found 10 to be mostly sufficient
n_flip: 20
token_constraints:
  _target_: tropt.optimizer.utils.token_constraints.TokenConstraints
  disallow_non_ascii: True
  disallow_special_tokens: True
use_retokenize: True
