_target_: tropt.optimizer.gcg_optimizer.GCGOptimizer
_partial_: true

# Original paper parameters:
num_steps: 500
n_candidates: 512
sample_topk: 256
sample_n_replace: 1
token_constraints:
  _target_: tropt.optimizer.utils.token_constraints.TokenConstraints
  disallow_non_ascii: True
  disallow_special_tokens: True
use_retokenize: True
