name: Deploy Sphinx documentation to Pages

on:
  push:
    branches:
      - main # or master, depending on your default branch name

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install sphinx sphinx-rtd-theme # Install Sphinx and your theme(s)
          if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi
      - name: Build HTML documentation
        run: sphinx-build -b html docs/source docs/build/html # Adjust paths as necessary
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
